// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentsByProvider = `-- name: CountAgentsByProvider :one
SELECT COUNT(*)::bigint FROM agents WHERE provider_id = $1
`

func (q *Queries) CountAgentsByProvider(ctx context.Context, providerID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentsByProvider, providerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1
`

func (q *Queries) DeleteAgent(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAgent, id)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT id, name, description, version, provider_id, default_model, created_at, updated_at
FROM agents
WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.ProviderID,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgent = `-- name: InsertAgent :one
INSERT INTO agents (
  id, name, description, version, provider_id, default_model, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, name, description, version, provider_id, default_model, created_at, updated_at
`

type InsertAgentParams struct {
	ID           string
	Name         string
	Description  string
	Version      int32
	ProviderID   string
	DefaultModel string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.ProviderID,
		arg.DefaultModel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.ProviderID,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgents = `-- name: ListAgents :many
SELECT id, name, description, version, provider_id, default_model, created_at, updated_at
FROM agents
ORDER BY created_at ASC
`

func (q *Queries) ListAgents(ctx context.Context) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.ProviderID,
			&i.DefaultModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByProvider = `-- name: ListAgentsByProvider :many
SELECT id, name, description, version, provider_id, default_model, created_at, updated_at
FROM agents
WHERE provider_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAgentsByProvider(ctx context.Context, providerID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.ProviderID,
			&i.DefaultModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET
  name = $2,
  description = $3,
  version = $4,
  provider_id = $5,
  default_model = $6,
  updated_at = $7
WHERE id = $1
RETURNING id, name, description, version, provider_id, default_model, created_at, updated_at
`

type UpdateAgentParams struct {
	ID           string
	Name         string
	Description  string
	Version      int32
	ProviderID   string
	DefaultModel string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.ProviderID,
		arg.DefaultModel,
		arg.UpdatedAt,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.ProviderID,
		&i.DefaultModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
