// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assistants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAssistantsByInferenceConnection = `-- name: CountAssistantsByInferenceConnection :one
SELECT COUNT(*)::bigint FROM assistants WHERE inference_connection_id = $1
`

func (q *Queries) CountAssistantsByInferenceConnection(ctx context.Context, inferenceConnectionID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAssistantsByInferenceConnection, inferenceConnectionID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAssistant = `-- name: DeleteAssistant :exec
DELETE FROM assistants WHERE id = $1
`

func (q *Queries) DeleteAssistant(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAssistant, id)
	return err
}

const getAssistant = `-- name: GetAssistant :one
SELECT
  a.id, a.name, a.description, a.version, a.inference_connection_id, a.default_model,
  a.settings, a.created_at, a.updated_at,
  c.name AS inference_connection_name
FROM assistants a
LEFT JOIN inference_connections c ON c.id = a.inference_connection_id
WHERE a.id = $1
`

type GetAssistantRow struct {
	ID                      string
	Name                    string
	Description             string
	Version                 int32
	InferenceConnectionID   *string
	DefaultModel            *string
	Settings                []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	InferenceConnectionName *string
}

func (q *Queries) GetAssistant(ctx context.Context, id string) (GetAssistantRow, error) {
	row := q.db.QueryRow(ctx, getAssistant, id)
	var i GetAssistantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.InferenceConnectionID,
		&i.DefaultModel,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InferenceConnectionName,
	)
	return i, err
}

const insertAssistant = `-- name: InsertAssistant :one
INSERT INTO assistants (
  id, name, description, version, inference_connection_id, default_model, settings, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, description, version, inference_connection_id, default_model, settings, created_at, updated_at
`

type InsertAssistantParams struct {
	ID                    string
	Name                  string
	Description           string
	Version               int32
	InferenceConnectionID *string
	DefaultModel          *string
	Settings              []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type InsertAssistantRow struct {
	ID                    string
	Name                  string
	Description           string
	Version               int32
	InferenceConnectionID *string
	DefaultModel          *string
	Settings              []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) InsertAssistant(ctx context.Context, arg InsertAssistantParams) (InsertAssistantRow, error) {
	row := q.db.QueryRow(ctx, insertAssistant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.InferenceConnectionID,
		arg.DefaultModel,
		arg.Settings,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InsertAssistantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.InferenceConnectionID,
		&i.DefaultModel,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssistants = `-- name: ListAssistants :many
SELECT
  a.id, a.name, a.description, a.version, a.inference_connection_id, a.default_model,
  a.settings, a.created_at, a.updated_at,
  c.name AS inference_connection_name
FROM assistants a
LEFT JOIN inference_connections c ON c.id = a.inference_connection_id
ORDER BY a.created_at ASC
`

type ListAssistantsRow struct {
	ID                      string
	Name                    string
	Description             string
	Version                 int32
	InferenceConnectionID   *string
	DefaultModel            *string
	Settings                []byte
	CreatedAt               pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
	InferenceConnectionName *string
}

func (q *Queries) ListAssistants(ctx context.Context) ([]ListAssistantsRow, error) {
	rows, err := q.db.Query(ctx, listAssistants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistantsRow
	for rows.Next() {
		var i ListAssistantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.InferenceConnectionID,
			&i.DefaultModel,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InferenceConnectionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssistantsByInferenceConnection = `-- name: ListAssistantsByInferenceConnection :many
SELECT id, name, description, version, inference_connection_id, default_model, settings, created_at, updated_at
FROM assistants
WHERE inference_connection_id = $1
ORDER BY created_at ASC
`

type ListAssistantsByInferenceConnectionRow struct {
	ID                    string
	Name                  string
	Description           string
	Version               int32
	InferenceConnectionID *string
	DefaultModel          *string
	Settings              []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) ListAssistantsByInferenceConnection(ctx context.Context, inferenceConnectionID *string) ([]ListAssistantsByInferenceConnectionRow, error) {
	rows, err := q.db.Query(ctx, listAssistantsByInferenceConnection, inferenceConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssistantsByInferenceConnectionRow
	for rows.Next() {
		var i ListAssistantsByInferenceConnectionRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.InferenceConnectionID,
			&i.DefaultModel,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAssistantsByInferenceConnection = `-- name: UnlinkAssistantsByInferenceConnection :exec
UPDATE assistants
SET
  inference_connection_id = NULL,
  default_model = NULL,
  version = version + 1,
  updated_at = $2
WHERE inference_connection_id = $1
`

type UnlinkAssistantsByInferenceConnectionParams struct {
	InferenceConnectionID *string
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) UnlinkAssistantsByInferenceConnection(ctx context.Context, arg UnlinkAssistantsByInferenceConnectionParams) error {
	_, err := q.db.Exec(ctx, unlinkAssistantsByInferenceConnection, arg.InferenceConnectionID, arg.UpdatedAt)
	return err
}

const updateAssistant = `-- name: UpdateAssistant :one
UPDATE assistants
SET
  name = $2,
  description = $3,
  version = $4,
  inference_connection_id = $5,
  default_model = $6,
  settings = $7,
  updated_at = $8
WHERE id = $1
RETURNING id, name, description, version, inference_connection_id, default_model, settings, created_at, updated_at
`

type UpdateAssistantParams struct {
	ID                    string
	Name                  string
	Description           string
	Version               int32
	InferenceConnectionID *string
	DefaultModel          *string
	Settings              []byte
	UpdatedAt             pgtype.Timestamptz
}

type UpdateAssistantRow struct {
	ID                    string
	Name                  string
	Description           string
	Version               int32
	InferenceConnectionID *string
	DefaultModel          *string
	Settings              []byte
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

func (q *Queries) UpdateAssistant(ctx context.Context, arg UpdateAssistantParams) (UpdateAssistantRow, error) {
	row := q.db.QueryRow(ctx, updateAssistant,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.InferenceConnectionID,
		arg.DefaultModel,
		arg.Settings,
		arg.UpdatedAt,
	)
	var i UpdateAssistantRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.InferenceConnectionID,
		&i.DefaultModel,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
