// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkpoints.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProjectCheckpoint = `-- name: GetProjectCheckpoint :one
SELECT id, project_id, sha, label, thread_id, message_id, created_at
FROM project_checkpoints
WHERE id = $1
`

func (q *Queries) GetProjectCheckpoint(ctx context.Context, id string) (ProjectCheckpoint, error) {
	row := q.db.QueryRow(ctx, getProjectCheckpoint, id)
	var i ProjectCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha,
		&i.Label,
		&i.ThreadID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const insertProjectCheckpoint = `-- name: InsertProjectCheckpoint :one
INSERT INTO project_checkpoints (
  id, project_id, sha, label, thread_id, message_id, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, sha, label, thread_id, message_id, created_at
`

type InsertProjectCheckpointParams struct {
	ID        string
	ProjectID string
	Sha       string
	Label     string
	ThreadID  *string
	MessageID *string
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertProjectCheckpoint(ctx context.Context, arg InsertProjectCheckpointParams) (ProjectCheckpoint, error) {
	row := q.db.QueryRow(ctx, insertProjectCheckpoint,
		arg.ID,
		arg.ProjectID,
		arg.Sha,
		arg.Label,
		arg.ThreadID,
		arg.MessageID,
		arg.CreatedAt,
	)
	var i ProjectCheckpoint
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Sha,
		&i.Label,
		&i.ThreadID,
		&i.MessageID,
		&i.CreatedAt,
	)
	return i, err
}

const listProjectCheckpoints = `-- name: ListProjectCheckpoints :many
SELECT id, project_id, sha, label, thread_id, message_id, created_at
FROM project_checkpoints
WHERE project_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectCheckpoints(ctx context.Context, projectID string) ([]ProjectCheckpoint, error) {
	rows, err := q.db.Query(ctx, listProjectCheckpoints, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProjectCheckpoint
	for rows.Next() {
		var i ProjectCheckpoint
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Sha,
			&i.Label,
			&i.ThreadID,
			&i.MessageID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
