// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, name, kind, spec, volume_name, created_at, updated_at
FROM environments
WHERE id = $1
`

func (q *Queries) GetEnvironment(ctx context.Context, id string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironment, id)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.VolumeName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertEnvironment = `-- name: InsertEnvironment :one
INSERT INTO environments (
  id, name, kind, spec, volume_name, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, kind, spec, volume_name, created_at, updated_at
`

type InsertEnvironmentParams struct {
	ID         string
	Name       string
	Kind       string
	Spec       []byte
	VolumeName *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertEnvironment(ctx context.Context, arg InsertEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, insertEnvironment,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Spec,
		arg.VolumeName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.VolumeName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
