// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: hop_captures.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteHopCapturesBySession = `-- name: DeleteHopCapturesBySession :exec
DELETE FROM hop_captures
WHERE thread_id = $1 AND session_id = $2 AND message_id IS NULL
`

type DeleteHopCapturesBySessionParams struct {
	ThreadID  string
	SessionID *string
}

func (q *Queries) DeleteHopCapturesBySession(ctx context.Context, arg DeleteHopCapturesBySessionParams) error {
	_, err := q.db.Exec(ctx, deleteHopCapturesBySession, arg.ThreadID, arg.SessionID)
	return err
}

const insertHopCapture = `-- name: InsertHopCapture :one
INSERT INTO hop_captures (
  id, thread_id, message_id, session_id, round_index, hop_kind, direction,
  method, url, status_code, headers_json, body_text, meta_json, created_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, thread_id, message_id, session_id, round_index, hop_kind, direction,
  method, url, status_code, headers_json, body_text, meta_json, created_at
`

type InsertHopCaptureParams struct {
	ID          string
	ThreadID    string
	MessageID   *string
	SessionID   *string
	RoundIndex  int32
	HopKind     string
	Direction   string
	Method      *string
	Url         *string
	StatusCode  *int32
	HeadersJson []byte
	BodyText    string
	MetaJson    []byte
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertHopCapture(ctx context.Context, arg InsertHopCaptureParams) (HopCapture, error) {
	row := q.db.QueryRow(ctx, insertHopCapture,
		arg.ID,
		arg.ThreadID,
		arg.MessageID,
		arg.SessionID,
		arg.RoundIndex,
		arg.HopKind,
		arg.Direction,
		arg.Method,
		arg.Url,
		arg.StatusCode,
		arg.HeadersJson,
		arg.BodyText,
		arg.MetaJson,
		arg.CreatedAt,
	)
	var i HopCapture
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.MessageID,
		&i.SessionID,
		&i.RoundIndex,
		&i.HopKind,
		&i.Direction,
		&i.Method,
		&i.Url,
		&i.StatusCode,
		&i.HeadersJson,
		&i.BodyText,
		&i.MetaJson,
		&i.CreatedAt,
	)
	return i, err
}

const linkHopCapturesToMessage = `-- name: LinkHopCapturesToMessage :exec
UPDATE hop_captures
SET message_id = $3
WHERE thread_id = $1 AND session_id = $2 AND message_id IS NULL
`

type LinkHopCapturesToMessageParams struct {
	ThreadID  string
	SessionID *string
	MessageID *string
}

func (q *Queries) LinkHopCapturesToMessage(ctx context.Context, arg LinkHopCapturesToMessageParams) error {
	_, err := q.db.Exec(ctx, linkHopCapturesToMessage, arg.ThreadID, arg.SessionID, arg.MessageID)
	return err
}

const listHopCapturesByMessage = `-- name: ListHopCapturesByMessage :many
SELECT id, thread_id, message_id, session_id, round_index, hop_kind, direction,
  method, url, status_code, headers_json, body_text, meta_json, created_at
FROM hop_captures
WHERE thread_id = $1 AND message_id = $2
ORDER BY round_index ASC, created_at ASC
`

type ListHopCapturesByMessageParams struct {
	ThreadID  string
	MessageID *string
}

func (q *Queries) ListHopCapturesByMessage(ctx context.Context, arg ListHopCapturesByMessageParams) ([]HopCapture, error) {
	rows, err := q.db.Query(ctx, listHopCapturesByMessage, arg.ThreadID, arg.MessageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HopCapture
	for rows.Next() {
		var i HopCapture
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.MessageID,
			&i.SessionID,
			&i.RoundIndex,
			&i.HopKind,
			&i.Direction,
			&i.Method,
			&i.Url,
			&i.StatusCode,
			&i.HeadersJson,
			&i.BodyText,
			&i.MetaJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHopCapturesByThread = `-- name: ListHopCapturesByThread :many
SELECT id, thread_id, message_id, session_id, round_index, hop_kind, direction,
  method, url, status_code, headers_json, body_text, meta_json, created_at
FROM hop_captures
WHERE thread_id = $1 AND message_id IS NOT NULL
ORDER BY created_at ASC, round_index ASC
`

func (q *Queries) ListHopCapturesByThread(ctx context.Context, threadID string) ([]HopCapture, error) {
	rows, err := q.db.Query(ctx, listHopCapturesByThread, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HopCapture
	for rows.Next() {
		var i HopCapture
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.MessageID,
			&i.SessionID,
			&i.RoundIndex,
			&i.HopKind,
			&i.Direction,
			&i.Method,
			&i.Url,
			&i.StatusCode,
			&i.HeadersJson,
			&i.BodyText,
			&i.MetaJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
