// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inference_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteInferenceConnection = `-- name: DeleteInferenceConnection :exec
DELETE FROM inference_connections WHERE id = $1
`

func (q *Queries) DeleteInferenceConnection(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteInferenceConnection, id)
	return err
}

const getInferenceConnection = `-- name: GetInferenceConnection :one
SELECT id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
FROM inference_connections
WHERE id = $1
`

func (q *Queries) GetInferenceConnection(ctx context.Context, id string) (InferenceConnection, error) {
	row := q.db.QueryRow(ctx, getInferenceConnection, id)
	var i InferenceConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertInferenceConnection = `-- name: InsertInferenceConnection :one
INSERT INTO inference_connections (
  id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
`

type InsertInferenceConnectionParams struct {
	ID              string
	Name            string
	Type            string
	BaseUrl         string
	ApiKey          string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertInferenceConnection(ctx context.Context, arg InsertInferenceConnectionParams) (InferenceConnection, error) {
	row := q.db.QueryRow(ctx, insertInferenceConnection,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Models,
		arg.ModelsUpdatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i InferenceConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInferenceConnections = `-- name: ListInferenceConnections :many
SELECT id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
FROM inference_connections
ORDER BY created_at ASC
`

func (q *Queries) ListInferenceConnections(ctx context.Context) ([]InferenceConnection, error) {
	rows, err := q.db.Query(ctx, listInferenceConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InferenceConnection
	for rows.Next() {
		var i InferenceConnection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Models,
			&i.ModelsUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInferenceConnection = `-- name: UpdateInferenceConnection :one
UPDATE inference_connections
SET
  name = $2,
  base_url = $3,
  api_key = $4,
  updated_at = $5
WHERE id = $1
RETURNING id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
`

type UpdateInferenceConnectionParams struct {
	ID        string
	Name      string
	BaseUrl   string
	ApiKey    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateInferenceConnection(ctx context.Context, arg UpdateInferenceConnectionParams) (InferenceConnection, error) {
	row := q.db.QueryRow(ctx, updateInferenceConnection,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.UpdatedAt,
	)
	var i InferenceConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateInferenceConnectionModels = `-- name: UpdateInferenceConnectionModels :one
UPDATE inference_connections
SET
  models = $2,
  models_updated_at = $3,
  updated_at = $4
WHERE id = $1
RETURNING id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
`

type UpdateInferenceConnectionModelsParams struct {
	ID              string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateInferenceConnectionModels(ctx context.Context, arg UpdateInferenceConnectionModelsParams) (InferenceConnection, error) {
	row := q.db.QueryRow(ctx, updateInferenceConnectionModels,
		arg.ID,
		arg.Models,
		arg.ModelsUpdatedAt,
		arg.UpdatedAt,
	)
	var i InferenceConnection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
