// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assistant struct {
	ID                    string
	Name                  string
	Description           string
	Version               int32
	InferenceConnectionID *string
	DefaultModel          *string
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	Settings              []byte
}

type HopCapture struct {
	ID          string
	ThreadID    string
	MessageID   *string
	SessionID   *string
	RoundIndex  int32
	HopKind     string
	Direction   string
	Method      *string
	Url         *string
	StatusCode  *int32
	HeadersJson []byte
	BodyText    string
	MetaJson    []byte
	CreatedAt   pgtype.Timestamptz
}

type InferenceConnection struct {
	ID              string
	Name            string
	Type            string
	BaseUrl         string
	ApiKey          string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Message struct {
	ID              string
	ThreadID        string
	Role            string
	Content         string
	Position        int32
	CreatedAt       pgtype.Timestamptz
	Parts           []byte
	Model           *string
	ProviderID      *string
	ProviderName    *string
	StopReason      *string
	Active          bool
	PromptMessageID *string
}

type PlaneSetting struct {
	ID           string
	Sandbox      []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Environment  []byte
	Integrations []byte
}

type Project struct {
	ID          string
	Name        string
	Description string
	Settings    []byte
	Remotes     []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type ProjectCheckpoint struct {
	ID        string
	ProjectID string
	Sha       string
	Label     string
	ThreadID  *string
	MessageID *string
	CreatedAt pgtype.Timestamptz
}

type Resource struct {
	ID        string
	Name      string
	Kind      string
	Spec      []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Thread struct {
	ID           string
	Title        string
	TitleSource  string
	AssistantID  *string
	CurrentModel *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ViewModeID   *string
	ProjectID    string
}
