// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: model_specs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getModelSpecs = `-- name: GetModelSpecs :one
SELECT id, source_url, sync_interval_hours, enabled, snapshot_source_url, etag, bytes,
       fetched_at, last_attempt_at, last_error, data
FROM model_specs
WHERE id = 'default'
`

func (q *Queries) GetModelSpecs(ctx context.Context) (ModelSpec, error) {
	row := q.db.QueryRow(ctx, getModelSpecs)
	var i ModelSpec
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SyncIntervalHours,
		&i.Enabled,
		&i.SnapshotSourceUrl,
		&i.Etag,
		&i.Bytes,
		&i.FetchedAt,
		&i.LastAttemptAt,
		&i.LastError,
		&i.Data,
	)
	return i, err
}

const recordModelSpecsError = `-- name: RecordModelSpecsError :exec
UPDATE model_specs
SET last_attempt_at = $1, last_error = $2
WHERE id = 'default'
`

type RecordModelSpecsErrorParams struct {
	LastAttemptAt pgtype.Timestamptz
	LastError     string
}

func (q *Queries) RecordModelSpecsError(ctx context.Context, arg RecordModelSpecsErrorParams) error {
	_, err := q.db.Exec(ctx, recordModelSpecsError, arg.LastAttemptAt, arg.LastError)
	return err
}

const saveModelSpecsSnapshot = `-- name: SaveModelSpecsSnapshot :exec
UPDATE model_specs
SET snapshot_source_url = $1, etag = $2, bytes = $3, fetched_at = $4,
    last_attempt_at = $4, last_error = '', data = $5
WHERE id = 'default'
`

type SaveModelSpecsSnapshotParams struct {
	SnapshotSourceUrl string
	Etag              string
	Bytes             int64
	FetchedAt         pgtype.Timestamptz
	Data              []byte
}

func (q *Queries) SaveModelSpecsSnapshot(ctx context.Context, arg SaveModelSpecsSnapshotParams) error {
	_, err := q.db.Exec(ctx, saveModelSpecsSnapshot,
		arg.SnapshotSourceUrl,
		arg.Etag,
		arg.Bytes,
		arg.FetchedAt,
		arg.Data,
	)
	return err
}

const touchModelSpecsSnapshot = `-- name: TouchModelSpecsSnapshot :exec
UPDATE model_specs
SET fetched_at = $1, last_attempt_at = $1, last_error = ''
WHERE id = 'default'
`

func (q *Queries) TouchModelSpecsSnapshot(ctx context.Context, fetchedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, touchModelSpecsSnapshot, fetchedAt)
	return err
}

const updateModelSpecsSettings = `-- name: UpdateModelSpecsSettings :exec
UPDATE model_specs
SET source_url = $1, sync_interval_hours = $2, enabled = $3
WHERE id = 'default'
`

type UpdateModelSpecsSettingsParams struct {
	SourceUrl         string
	SyncIntervalHours int32
	Enabled           bool
}

func (q *Queries) UpdateModelSpecsSettings(ctx context.Context, arg UpdateModelSpecsSettingsParams) error {
	_, err := q.db.Exec(ctx, updateModelSpecsSettings, arg.SourceUrl, arg.SyncIntervalHours, arg.Enabled)
	return err
}
