// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           string
	Name         string
	Description  string
	Version      int32
	ProviderID   *string
	DefaultModel *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Environment struct {
	ID         string
	Name       string
	Kind       string
	Spec       []byte
	VolumeName *string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Message struct {
	ID           string
	ThreadID     string
	Role         string
	Content      string
	Position     int32
	CreatedAt    pgtype.Timestamptz
	Parts        []byte
	Model        *string
	ProviderID   *string
	ProviderName *string
	StopReason   *string
}

type Project struct {
	ID            string
	Name          string
	Description   string
	Isolation     string
	EnvironmentID *string
	Settings      []byte
	Remotes       []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Provider struct {
	ID              string
	Name            string
	Type            string
	BaseUrl         string
	ApiKey          string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type Thread struct {
	ID           string
	Title        string
	TitleSource  string
	AgentID      *string
	CurrentModel *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	ViewModeID   *string
	ProjectID    string
}
