// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	ID           string
	Name         string
	Description  string
	Version      int32
	ProviderID   string
	DefaultModel string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Provider struct {
	ID              string
	Name            string
	Type            string
	BaseUrl         string
	ApiKey          string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}
