// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countThreadsByProject = `-- name: CountThreadsByProject :one
SELECT count(*) FROM threads WHERE project_id = $1
`

func (q *Queries) CountThreadsByProject(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countThreadsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteProject = `-- name: DeleteProject :exec
DELETE FROM projects WHERE id = $1
`

func (q *Queries) DeleteProject(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const deleteThreadsByProject = `-- name: DeleteThreadsByProject :exec
DELETE FROM threads WHERE project_id = $1
`

func (q *Queries) DeleteThreadsByProject(ctx context.Context, projectID string) error {
	_, err := q.db.Exec(ctx, deleteThreadsByProject, projectID)
	return err
}

const getDefaultProject = `-- name: GetDefaultProject :one
SELECT id, name, description, isolation, environment_id, settings, remotes, created_at, updated_at
FROM projects
WHERE name = 'Default'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetDefaultProject(ctx context.Context) (Project, error) {
	row := q.db.QueryRow(ctx, getDefaultProject)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Isolation,
		&i.EnvironmentID,
		&i.Settings,
		&i.Remotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, name, description, isolation, environment_id, settings, remotes, created_at, updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id string) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Isolation,
		&i.EnvironmentID,
		&i.Settings,
		&i.Remotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProject = `-- name: InsertProject :one
INSERT INTO projects (
  id, name, description, isolation, environment_id, settings, remotes, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, description, isolation, environment_id, settings, remotes, created_at, updated_at
`

type InsertProjectParams struct {
	ID            string
	Name          string
	Description   string
	Isolation     string
	EnvironmentID *string
	Settings      []byte
	Remotes       []byte
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) InsertProject(ctx context.Context, arg InsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, insertProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Isolation,
		arg.EnvironmentID,
		arg.Settings,
		arg.Remotes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Isolation,
		&i.EnvironmentID,
		&i.Settings,
		&i.Remotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, description, isolation, environment_id, settings, remotes, created_at, updated_at
FROM projects
ORDER BY created_at ASC
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Isolation,
			&i.EnvironmentID,
			&i.Settings,
			&i.Remotes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
  name = $2,
  description = $3,
  isolation = $4,
  environment_id = $5,
  settings = $6,
  remotes = $7,
  updated_at = $8
WHERE id = $1
RETURNING id, name, description, isolation, environment_id, settings, remotes, created_at, updated_at
`

type UpdateProjectParams struct {
	ID            string
	Name          string
	Description   string
	Isolation     string
	EnvironmentID *string
	Settings      []byte
	Remotes       []byte
	UpdatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Isolation,
		arg.EnvironmentID,
		arg.Settings,
		arg.Remotes,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Isolation,
		&i.EnvironmentID,
		&i.Settings,
		&i.Remotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
