// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteProvider = `-- name: DeleteProvider :exec
DELETE FROM providers WHERE id = $1
`

func (q *Queries) DeleteProvider(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteProvider, id)
	return err
}

const getProvider = `-- name: GetProvider :one
SELECT id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
FROM providers
WHERE id = $1
`

func (q *Queries) GetProvider(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProvider, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderForUpdate = `-- name: GetProviderForUpdate :one
SELECT id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
FROM providers
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetProviderForUpdate(ctx context.Context, id string) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderForUpdate, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertProvider = `-- name: InsertProvider :one
INSERT INTO providers (
  id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
`

type InsertProviderParams struct {
	ID              string
	Name            string
	Type            string
	BaseUrl         string
	ApiKey          string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertProvider(ctx context.Context, arg InsertProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, insertProvider,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.BaseUrl,
		arg.ApiKey,
		arg.Models,
		arg.ModelsUpdatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
FROM providers
ORDER BY created_at ASC
`

func (q *Queries) ListProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, listProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Provider
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.BaseUrl,
			&i.ApiKey,
			&i.Models,
			&i.ModelsUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET
  name = $2,
  base_url = $3,
  api_key = $4,
  updated_at = $5
WHERE id = $1
RETURNING id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
`

type UpdateProviderParams struct {
	ID        string
	Name      string
	BaseUrl   string
	ApiKey    string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.ID,
		arg.Name,
		arg.BaseUrl,
		arg.ApiKey,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProviderModels = `-- name: UpdateProviderModels :one
UPDATE providers
SET
  models = $2,
  models_updated_at = $3,
  updated_at = $4
WHERE id = $1
RETURNING id, name, type, base_url, api_key, models, models_updated_at, created_at, updated_at
`

type UpdateProviderModelsParams struct {
	ID              string
	Models          []byte
	ModelsUpdatedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateProviderModels(ctx context.Context, arg UpdateProviderModelsParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderModels,
		arg.ID,
		arg.Models,
		arg.ModelsUpdatedAt,
		arg.UpdatedAt,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.BaseUrl,
		&i.ApiKey,
		&i.Models,
		&i.ModelsUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
