// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = $1
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, name, kind, spec, created_at, updated_at
FROM resources
WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertResource = `-- name: InsertResource :one
INSERT INTO resources (id, name, kind, spec, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, kind, spec, created_at, updated_at
`

type InsertResourceParams struct {
	ID        string
	Name      string
	Kind      string
	Spec      []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertResource(ctx context.Context, arg InsertResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, insertResource,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Spec,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, name, kind, spec, created_at, updated_at
FROM resources
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Spec,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET name = $2, spec = $3, updated_at = $4
WHERE id = $1
RETURNING id, name, kind, spec, created_at, updated_at
`

type UpdateResourceParams struct {
	ID        string
	Name      string
	Spec      []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Name,
		arg.Spec,
		arg.UpdatedAt,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Spec,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
