// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllThreads = `-- name: CountAllThreads :one
SELECT count(*) FROM threads
`

func (q *Queries) CountAllThreads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllThreads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonDefaultProjects = `-- name: CountNonDefaultProjects :one
SELECT count(*) FROM projects WHERE name <> 'Default'
`

func (q *Queries) CountNonDefaultProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNonDefaultProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlaneIntegrations = `-- name: GetPlaneIntegrations :one
SELECT integrations
FROM plane_settings
WHERE id = 'default'
`

func (q *Queries) GetPlaneIntegrations(ctx context.Context) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlaneIntegrations)
	var integrations []byte
	err := row.Scan(&integrations)
	return integrations, err
}

const getPlaneSettings = `-- name: GetPlaneSettings :one
SELECT id, sandbox, environment, created_at, updated_at
FROM plane_settings
WHERE id = 'default'
`

type GetPlaneSettingsRow struct {
	ID          string
	Sandbox     []byte
	Environment []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetPlaneSettings(ctx context.Context) (GetPlaneSettingsRow, error) {
	row := q.db.QueryRow(ctx, getPlaneSettings)
	var i GetPlaneSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Sandbox,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlaneSettings = `-- name: InsertPlaneSettings :one
INSERT INTO plane_settings (id, sandbox, environment, created_at, updated_at)
VALUES ('default', $1, '{}'::jsonb, $2, $3)
RETURNING id, sandbox, environment, created_at, updated_at
`

type InsertPlaneSettingsParams struct {
	Sandbox   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type InsertPlaneSettingsRow struct {
	ID          string
	Sandbox     []byte
	Environment []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) InsertPlaneSettings(ctx context.Context, arg InsertPlaneSettingsParams) (InsertPlaneSettingsRow, error) {
	row := q.db.QueryRow(ctx, insertPlaneSettings, arg.Sandbox, arg.CreatedAt, arg.UpdatedAt)
	var i InsertPlaneSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Sandbox,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaneIntegrations = `-- name: UpdatePlaneIntegrations :exec
UPDATE plane_settings
SET integrations = $1, updated_at = $2
WHERE id = 'default'
`

type UpdatePlaneIntegrationsParams struct {
	Integrations []byte
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdatePlaneIntegrations(ctx context.Context, arg UpdatePlaneIntegrationsParams) error {
	_, err := q.db.Exec(ctx, updatePlaneIntegrations, arg.Integrations, arg.UpdatedAt)
	return err
}

const updatePlaneSettings = `-- name: UpdatePlaneSettings :one
UPDATE plane_settings
SET sandbox = $1, environment = $2, updated_at = $3
WHERE id = 'default'
RETURNING id, sandbox, environment, created_at, updated_at
`

type UpdatePlaneSettingsParams struct {
	Sandbox     []byte
	Environment []byte
	UpdatedAt   pgtype.Timestamptz
}

type UpdatePlaneSettingsRow struct {
	ID          string
	Sandbox     []byte
	Environment []byte
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdatePlaneSettings(ctx context.Context, arg UpdatePlaneSettingsParams) (UpdatePlaneSettingsRow, error) {
	row := q.db.QueryRow(ctx, updatePlaneSettings, arg.Sandbox, arg.Environment, arg.UpdatedAt)
	var i UpdatePlaneSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Sandbox,
		&i.Environment,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
