// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllThreads = `-- name: CountAllThreads :one
SELECT count(*) FROM threads
`

func (q *Queries) CountAllThreads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllThreads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNonPersonalProjects = `-- name: CountNonPersonalProjects :one
SELECT count(*) FROM projects WHERE name <> 'Personal'
`

func (q *Queries) CountNonPersonalProjects(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNonPersonalProjects)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPlaneSettings = `-- name: GetPlaneSettings :one
SELECT id, sandbox, created_at, updated_at
FROM plane_settings
WHERE id = 'default'
`

func (q *Queries) GetPlaneSettings(ctx context.Context) (PlaneSetting, error) {
	row := q.db.QueryRow(ctx, getPlaneSettings)
	var i PlaneSetting
	err := row.Scan(
		&i.ID,
		&i.Sandbox,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlaneSettings = `-- name: InsertPlaneSettings :one
INSERT INTO plane_settings (id, sandbox, created_at, updated_at)
VALUES ('default', $1, $2, $3)
RETURNING id, sandbox, created_at, updated_at
`

type InsertPlaneSettingsParams struct {
	Sandbox   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) InsertPlaneSettings(ctx context.Context, arg InsertPlaneSettingsParams) (PlaneSetting, error) {
	row := q.db.QueryRow(ctx, insertPlaneSettings, arg.Sandbox, arg.CreatedAt, arg.UpdatedAt)
	var i PlaneSetting
	err := row.Scan(
		&i.ID,
		&i.Sandbox,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlaneSettings = `-- name: UpdatePlaneSettings :one
UPDATE plane_settings
SET sandbox = $1, updated_at = $2
WHERE id = 'default'
RETURNING id, sandbox, created_at, updated_at
`

type UpdatePlaneSettingsParams struct {
	Sandbox   []byte
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdatePlaneSettings(ctx context.Context, arg UpdatePlaneSettingsParams) (PlaneSetting, error) {
	row := q.db.QueryRow(ctx, updatePlaneSettings, arg.Sandbox, arg.UpdatedAt)
	var i PlaneSetting
	err := row.Scan(
		&i.ID,
		&i.Sandbox,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
