// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countThreadsByAgent = `-- name: CountThreadsByAgent :one
SELECT count(*) FROM threads WHERE agent_id = $1
`

func (q *Queries) CountThreadsByAgent(ctx context.Context, agentID *string) (int64, error) {
	row := q.db.QueryRow(ctx, countThreadsByAgent, agentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getThread = `-- name: GetThread :one
SELECT id, title, title_source, agent_id, current_model, created_at, updated_at
FROM threads
WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id string) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSource,
		&i.AgentID,
		&i.CurrentModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (id, thread_id, role, content, position, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, thread_id, role, content, position, created_at
`

type InsertMessageParams struct {
	ID        string
	ThreadID  string
	Role      string
	Content   string
	Position  int32
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ID,
		arg.ThreadID,
		arg.Role,
		arg.Content,
		arg.Position,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.Role,
		&i.Content,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertThread = `-- name: InsertThread :one
INSERT INTO threads (
  id, title, title_source, agent_id, current_model, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, title, title_source, agent_id, current_model, created_at, updated_at
`

type InsertThreadParams struct {
	ID           string
	Title        string
	TitleSource  string
	AgentID      *string
	CurrentModel *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) InsertThread(ctx context.Context, arg InsertThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, insertThread,
		arg.ID,
		arg.Title,
		arg.TitleSource,
		arg.AgentID,
		arg.CurrentModel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSource,
		&i.AgentID,
		&i.CurrentModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMessages = `-- name: ListMessages :many
SELECT id, thread_id, role, content, position, created_at
FROM messages
WHERE thread_id = $1
ORDER BY position ASC
`

func (q *Queries) ListMessages(ctx context.Context, threadID string) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessages, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ThreadID,
			&i.Role,
			&i.Content,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT
  t.id,
  t.title,
  t.title_source,
  t.agent_id,
  t.current_model,
  t.created_at,
  t.updated_at,
  (SELECT count(*)::int FROM messages m WHERE m.thread_id = t.id) AS message_count
FROM threads t
ORDER BY t.updated_at DESC
`

type ListThreadsRow struct {
	ID           string
	Title        string
	TitleSource  string
	AgentID      *string
	CurrentModel *string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	MessageCount int32
}

func (q *Queries) ListThreads(ctx context.Context) ([]ListThreadsRow, error) {
	rows, err := q.db.Query(ctx, listThreads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadsRow
	for rows.Next() {
		var i ListThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TitleSource,
			&i.AgentID,
			&i.CurrentModel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessagePosition = `-- name: NextMessagePosition :one
SELECT COALESCE(MAX(position), -1)::int AS max_position
FROM messages
WHERE thread_id = $1
`

func (q *Queries) NextMessagePosition(ctx context.Context, threadID string) (int32, error) {
	row := q.db.QueryRow(ctx, nextMessagePosition, threadID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const pinThreadAgent = `-- name: PinThreadAgent :one
UPDATE threads
SET agent_id = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, title_source, agent_id, current_model, created_at, updated_at
`

type PinThreadAgentParams struct {
	ID        string
	AgentID   *string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) PinThreadAgent(ctx context.Context, arg PinThreadAgentParams) (Thread, error) {
	row := q.db.QueryRow(ctx, pinThreadAgent, arg.ID, arg.AgentID, arg.UpdatedAt)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSource,
		&i.AgentID,
		&i.CurrentModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const renameThread = `-- name: RenameThread :one
UPDATE threads
SET title = $2, title_source = $3, updated_at = $4
WHERE id = $1
RETURNING id, title, title_source, agent_id, current_model, created_at, updated_at
`

type RenameThreadParams struct {
	ID          string
	Title       string
	TitleSource string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) RenameThread(ctx context.Context, arg RenameThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, renameThread,
		arg.ID,
		arg.Title,
		arg.TitleSource,
		arg.UpdatedAt,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSource,
		&i.AgentID,
		&i.CurrentModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setThreadModel = `-- name: SetThreadModel :one
UPDATE threads
SET current_model = $2, updated_at = $3
WHERE id = $1
RETURNING id, title, title_source, agent_id, current_model, created_at, updated_at
`

type SetThreadModelParams struct {
	ID           string
	CurrentModel *string
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) SetThreadModel(ctx context.Context, arg SetThreadModelParams) (Thread, error) {
	row := q.db.QueryRow(ctx, setThreadModel, arg.ID, arg.CurrentModel, arg.UpdatedAt)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TitleSource,
		&i.AgentID,
		&i.CurrentModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setThreadTitleIfAuto = `-- name: SetThreadTitleIfAuto :exec
UPDATE threads
SET title = $2, updated_at = $3
WHERE id = $1 AND title_source = 'auto'
`

type SetThreadTitleIfAutoParams struct {
	ID        string
	Title     string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) SetThreadTitleIfAuto(ctx context.Context, arg SetThreadTitleIfAutoParams) error {
	_, err := q.db.Exec(ctx, setThreadTitleIfAuto, arg.ID, arg.Title, arg.UpdatedAt)
	return err
}

const touchThread = `-- name: TouchThread :exec
UPDATE threads SET updated_at = $2 WHERE id = $1
`

type TouchThreadParams struct {
	ID        string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) TouchThread(ctx context.Context, arg TouchThreadParams) error {
	_, err := q.db.Exec(ctx, touchThread, arg.ID, arg.UpdatedAt)
	return err
}
