// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteToolIntegration = `-- name: DeleteToolIntegration :exec
DELETE FROM tool_integrations WHERE id = $1
`

func (q *Queries) DeleteToolIntegration(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteToolIntegration, id)
	return err
}

const getPlaneToolDefaults = `-- name: GetPlaneToolDefaults :one
SELECT web_search_integration_id, fetch_page_integration_id
FROM plane_settings
WHERE id = 'default'
`

type GetPlaneToolDefaultsRow struct {
	WebSearchIntegrationID *string
	FetchPageIntegrationID *string
}

func (q *Queries) GetPlaneToolDefaults(ctx context.Context) (GetPlaneToolDefaultsRow, error) {
	row := q.db.QueryRow(ctx, getPlaneToolDefaults)
	var i GetPlaneToolDefaultsRow
	err := row.Scan(&i.WebSearchIntegrationID, &i.FetchPageIntegrationID)
	return i, err
}

const getToolIntegration = `-- name: GetToolIntegration :one
SELECT id, name, kind, enabled, scope, endpoint, mode, capabilities, config, secrets,
       health_status, health_checked_at, created_at, updated_at
FROM tool_integrations
WHERE id = $1
`

func (q *Queries) GetToolIntegration(ctx context.Context, id string) (ToolIntegration, error) {
	row := q.db.QueryRow(ctx, getToolIntegration, id)
	var i ToolIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Scope,
		&i.Endpoint,
		&i.Mode,
		&i.Capabilities,
		&i.Config,
		&i.Secrets,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertToolIntegration = `-- name: InsertToolIntegration :one
INSERT INTO tool_integrations (
  id, name, kind, enabled, scope, endpoint, mode, capabilities, config, secrets,
  health_status, health_checked_at, created_at, updated_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, name, kind, enabled, scope, endpoint, mode, capabilities, config, secrets,
          health_status, health_checked_at, created_at, updated_at
`

type InsertToolIntegrationParams struct {
	ID              string
	Name            string
	Kind            string
	Enabled         bool
	Scope           string
	Endpoint        string
	Mode            string
	Capabilities    []byte
	Config          []byte
	Secrets         []byte
	HealthStatus    string
	HealthCheckedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) InsertToolIntegration(ctx context.Context, arg InsertToolIntegrationParams) (ToolIntegration, error) {
	row := q.db.QueryRow(ctx, insertToolIntegration,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Enabled,
		arg.Scope,
		arg.Endpoint,
		arg.Mode,
		arg.Capabilities,
		arg.Config,
		arg.Secrets,
		arg.HealthStatus,
		arg.HealthCheckedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i ToolIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Scope,
		&i.Endpoint,
		&i.Mode,
		&i.Capabilities,
		&i.Config,
		&i.Secrets,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listToolIntegrations = `-- name: ListToolIntegrations :many
SELECT id, name, kind, enabled, scope, endpoint, mode, capabilities, config, secrets,
       health_status, health_checked_at, created_at, updated_at
FROM tool_integrations
ORDER BY created_at ASC
`

func (q *Queries) ListToolIntegrations(ctx context.Context) ([]ToolIntegration, error) {
	rows, err := q.db.Query(ctx, listToolIntegrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ToolIntegration
	for rows.Next() {
		var i ToolIntegration
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.Scope,
			&i.Endpoint,
			&i.Mode,
			&i.Capabilities,
			&i.Config,
			&i.Secrets,
			&i.HealthStatus,
			&i.HealthCheckedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaneToolDefaults = `-- name: UpdatePlaneToolDefaults :exec
UPDATE plane_settings
SET
  web_search_integration_id = $1,
  fetch_page_integration_id = $2,
  updated_at = $3
WHERE id = 'default'
`

type UpdatePlaneToolDefaultsParams struct {
	WebSearchIntegrationID *string
	FetchPageIntegrationID *string
	UpdatedAt              pgtype.Timestamptz
}

func (q *Queries) UpdatePlaneToolDefaults(ctx context.Context, arg UpdatePlaneToolDefaultsParams) error {
	_, err := q.db.Exec(ctx, updatePlaneToolDefaults, arg.WebSearchIntegrationID, arg.FetchPageIntegrationID, arg.UpdatedAt)
	return err
}

const updateToolIntegration = `-- name: UpdateToolIntegration :one
UPDATE tool_integrations
SET
  name = $2,
  enabled = $3,
  endpoint = $4,
  mode = $5,
  capabilities = $6,
  config = $7,
  secrets = $8,
  health_status = $9,
  health_checked_at = $10,
  updated_at = $11
WHERE id = $1
RETURNING id, name, kind, enabled, scope, endpoint, mode, capabilities, config, secrets,
          health_status, health_checked_at, created_at, updated_at
`

type UpdateToolIntegrationParams struct {
	ID              string
	Name            string
	Enabled         bool
	Endpoint        string
	Mode            string
	Capabilities    []byte
	Config          []byte
	Secrets         []byte
	HealthStatus    string
	HealthCheckedAt pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) UpdateToolIntegration(ctx context.Context, arg UpdateToolIntegrationParams) (ToolIntegration, error) {
	row := q.db.QueryRow(ctx, updateToolIntegration,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Endpoint,
		arg.Mode,
		arg.Capabilities,
		arg.Config,
		arg.Secrets,
		arg.HealthStatus,
		arg.HealthCheckedAt,
		arg.UpdatedAt,
	)
	var i ToolIntegration
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Scope,
		&i.Endpoint,
		&i.Mode,
		&i.Capabilities,
		&i.Config,
		&i.Secrets,
		&i.HealthStatus,
		&i.HealthCheckedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
